// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SpecialStatus","status":true,"description":"TPが一定以上の時に勝手にステータスが追加される。","parameters":{"ステータスID":"11","TP値":"100"}},
{"name":"SpecialSkill","status":true,"description":"TPが一定以上の時だけ、出るバトルコマンドが設定することが出来る。","parameters":{"TP値":"100"}},
{"name":"SpecialAttack","status":true,"description":"アニメーションを連続で表示して必殺技っぽい感じにする。","parameters":{}},
{"name":"SimpleMsgSideView","status":true,"description":"サイドビューバトルで技/アイテムの名前のみ表示します。","parameters":{"displayAttack":"0","position":"1"}},
{"name":"scrollText","status":true,"description":"文章のスクロール表示が出来ないの対応プラグイン","parameters":{}}
];
